const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;

const DEFAULT_RELATIVE_FORMAT = 'd MMMM yyyy';

const SINGLE_QUOTE = '\u0027';

export {
  DEFAULT_RELATIVE_FORMAT,
  MILLISECONDS_IN_SECOND,
  SECONDS_IN_MINUTE,
  SINGLE_QUOTE,
};
