version: '3'

services:
  postgres:
    image: 'postgres:15.4'
    ports:
      - 7433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: serenity
