FROM node:18.16.0 as backend-builder

WORKDIR /app
COPY ./package*.json ./tsconfig.json  ./
COPY ./shared/ ./shared/
COPY ./backend/package.json ./backend/package.json
RUN npm ci

COPY ./backend/ ./backend/
RUN npm run build:backend

EXPOSE 3001
CMD npm start -w backend
