FROM node:18.16.0 as backend-builder

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG HOST
ENV HOST=$HOST
ARG PORT
ENV PORT=$PORT

WORKDIR /app
COPY ./package*.json ./tsconfig.json  ./
COPY ./shared/ ./shared/
COPY ./backend/package.json ./backend/package.json
RUN npm ci

COPY ./backend/ ./backend/
RUN npm run build:backend

EXPOSE 3001
CMD npm start -w backend
