parserOptions:
  project:
    - ./tsconfig.json

settings:
  react:
    version: 'detect'
  import/ignore:
    - "node_modules/react-native/index\\.js$"

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  import/extensions:
    - off
  react/self-closing-comp:
    - error
