name: Continuous Integration Docker Build

on:
  pull_request:
    branches:
      - development
      - production
    paths:
      - frontend/**/*.*
      - backend/**/*.*
      - shared/**/*.*

  workflow_dispatch:

concurrency:
  group: ci-build-docker-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-build-docker-images:
    name: Build backend and frontend docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build backend image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: calmpal-backend
          push_image_and_stages: false
          context: ./
          dockerfile: ./backend/Dockerfile.development
          build_extra_args: '--build-arg NODE_ENV=development --build-arg HOST=localhost --build-arg PORT=3001'
      - name: Build frontend image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: calmpal-frontend
          push_image_and_stages: false
          context: ./
          dockerfile: ./frontend/Dockerfile.development
          build_extra_args: '--build-arg NODE_ENV=development --build-arg VITE_APP_API_ORIGIN_URL=/api/v1 --build-arg VITE_APP_PROXY_SERVER_URL=http://localhost:3001'
