name: Continuous Integration Database Migration

env:
  NODE_ENV: local
  HOST: localhost
  PORT: 3001
  DB_NAME: calmpal_db
  DB_USERNAME: postgres
  DB_PASSWORD: password
  DB_PORT: 5434
  DB_DIALECT: pg
  DB_POOL_MIN: 2
  DB_POOL_MAX: 10
  DUMP_FILE: environment-dump

on:
  pull_request:
    branches:
      - development
    paths:
      - backend/**/*.*

  workflow_dispatch:

concurrency:
  group: ci-db-migration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-run-db-migration:
    name: Run latest database migration on environment dump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            ENVIRONMENT, ${{ secrets.AWS_APP_DEVELOPMENT_SECRET }}
            ENVIRONMENT_DB, ${{ secrets.AWS_DB_SECRET }}
          parse-json-secrets: true

      - name: Setup docker services
        run: |
          docker compose -f docker-compose.services.yml up -d calmpal_db

      - name: Set Host IP environment variable
        id: get-docker-ip
        run: echo "HOST_IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV

      - name: Figure out whether migrations can be applied to existing environment database
        env:
          JWT_SECRET_KEY: ${{ env.ENVIRONMENT_JWT_SECRET }}
          AWS_REGION: ${{ env.ENVIRONMENT_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.ENVIRONMENT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.ENVIRONMENT_AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ env.ENVIRONMENT_AWS_BUCKET_NAME }}
          OPEN_AI_API_KEY: ${{ env.ENVIRONMENT_OPEN_AI_API_KEY }}
          BASE_OPEN_AI_URL: ${{ env.ENVIRONMENT_BASE_OPEN_AI_URL }}
          DB_HOST: ${{ env.HOST_IP }}
        run: |
          env > ./backend/.env

          docker build -t db-migrations-image \
          --build-arg ENVIRONMENT_DB_PASSWORD=$ENVIRONMENT_DB_PASSWORD \
          --build-arg ENVIRONMENT_DB_USERNAME=$ENVIRONMENT_DB_USERNAME \
          --build-arg ENVIRONMENT_DB_HOST=$ENVIRONMENT_DB_HOST \
          --build-arg ENVIRONMENT_DB_PORT=$ENVIRONMENT_DB_PORT \
          --build-arg ENVIRONMENT_DB_NAME=$ENVIRONMENT_DB_NAME \
          --build-arg DUMP_FILE=$DUMP_FILE \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_USERNAME=$DB_USERNAME \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_NAME=$DB_NAME \
          -f ./backend/Dockerfile.db-migrations .

          docker run --rm --env-file ./backend/.env db-migrations-image

      - name: Stop docker services
        run: docker compose -f docker-compose.services.yml down
