name: Continuous Integration Postman Run Tests Development

on:
  pull_request:
    branches:
      - development
    paths:
      - backend/**/*.*
      - shared/**/*.*

  workflow_dispatch:

concurrency:
  group: ci-postman-tests-${{ github.ref_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-postman-tests:
    name: Run latest database migration on environment dump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Run postman collection tests
        run: |
          docker run --rm -v ./:/etc/newman -t postman/newman run ./.postman/Calmpal.postman_collection.json
